server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoshuojun2019/huimei
          username: xiaoshuojun2019
          password: xsj@cheche365
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: leyou


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
